### ISSUE TITLE
`ReferenceError: document is not defined` on `spago run`

### ISSUE THREAD

**Issue by benjaminweb** [easafe/purescript-flame#81]
Minimal reproducible example:

```mkdir flame-micro
spago init
spago install flame
cd flame micro
# counter example from https://github.com/easafe/purescript-flame to src/Main.purs
spago run
```

Output:
```
[501 of 501] Compiling Main
[info] Build succeeded.
file:///Users/benjamin/repos/experiments/flame-micro/output/Flame.Application.Internal.Dom/foreign.js:3
    return document.querySelector(selector);
    ^

ReferenceError: document is not defined
    at Module.querySelector_ (file:///Users/benjamin/repos/experiments/flame-micro/output/Flame.Application.Internal.Dom/foreign.js:3:5)
    at __do (file:///Users/benjamin/repos/experiments/flame-micro/output/Flame.Application.Internal.Dom/index.js:9:33)
    at __do (file:///Users/benjamin/repos/experiments/flame-micro/output/Flame.Application.EffectList/index.js:144:87)
    at file:///Users/benjamin/repos/experiments/flame-micro/.spago/run.js:3:1
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.5.0
[error] Running failed; exit code: 1
```

**Comment by easafe** [comment]
Hi @benjaminweb ,

All examples should be run as web pages. As far as I know, ```spago run``` executes a node script.
